#!/bin/bash

Aufgabe1:

a)Ken Thompson,Dennis Ritchie,Brian W.Kernighan

b)Linus Torvalds

c)Computer Systems Research Group,1978 1BSD,1979 3BSD,1980 4BSD,
  1983 4.3BSD,1991 Net/2,USL v.BSDI,4.4BSD-Lite,BSD-Lite2 

d)"GNU" are packages from GNU project:shell,compiler,coreutils,glibc,etc

e)Richard Stallman

Aufgabe2:

a)date

b)wc -w loremIpsum 

c)/etc

d)/home/st/download/01task/partOne

e)which grep

f)2016 ls -l `which grep`

g)Script schreiben mit vim Editor;mit Arguments z.B.$1,$2,....$9;Befehl z.B. set or export benutzen

h)user group other.z.B.1.for user is the file readable,not writable,executable
  1.531 2.735 3.533 4.351

i)directory

k)cp mv mkdir

k)read the fxxking manual

Aufgabe 3:
a)grep African bigFive

b)grep '[Aa]frican' bigFive

c)grep -r african partOne

d)grep -n African bigFive

e)find partOne -name '[abc]'

f)find partOne -name '[abc]' -exec chmod 755 {} \;
